# Generated by Django 4.1.4 on 2022-12-29 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="author",),
        migrations.RemoveField(model_name="post", name="name",),
        migrations.RemoveField(model_name="post", name="slug",),
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, upload_to="users/%Y/%m/%d/"),
        ),
        migrations.AlterField(
            model_name="post", name="title", field=models.CharField(max_length=200),
        ),
    ]
