# Generated by Django 4.1.4 on 2022-12-29 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_remove_post_author_remove_post_name_remove_post_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(upload_to="img/%y"),
        ),
    ]
